Use letsencrypt by default and allow to change root ca with environme…
piku/piku pull request #231
Opened 2022-03-06 12:52 UTC by mlainez

As stated [here](https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA), Acme.sh uses ZeroSSL as default CA, which requires a one time login and doesn't work out of the box with piku.

The proposed PR switches back to `letsencrypt.org as` default root CA and offers the possibility to force another CA using an environment variable.

2022-03-06 23:42 UTC, chr15m requested changes
Good idea. LGTM but can you change the env var to `ACME_ROOT_CA` and add to the ENV.md documentation?

2022-03-07 09:09 UTC, mlainez commented
Requested changes have just been pushed. Let me know if it still requires adjustments.

2022-03-07 11:35 UTC, chr15m approved these changes
LGTM :+1:

2022-04-02 20:32 UTC, merged

2022-04-02 20:32 UTC, rcarmo commented
Thanks! Apologies for the time it took to get this in.

2022-04-03 00:20 UTC, chr15m commented
Hey, it's a hobby and your time is valuable. No need to apologize.